Exclude test utils class from tests
If not ignored ConfigSetupUtils is considered a test suite
and an initializationError is thrown because of the multiple
class constructor:

java.lang.IllegalArgumentException: Test class can only have one constructor

Change-Id: Ieae27e635ea1c3d0a3a884ef3240bacb6fcc8028